# Generated by Django 6.0.3 on 2026-03-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='wire_code',
        ),
        migrations.CreateModel(
            name='EmployeeWireCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wire_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_codes', to='core.employee')),
            ],
            options={
                'db_table': 'employee_wire_code',
            },
        ),
    ]
