# Generated by Django 6.0.3 on 2026-04-01 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_wire_code_employeewirecode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='client_dime_wire_co_6e0032_idx',
            old_name='client_dime_wire_co_bf3abe_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='wire_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='wire_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['employee'], name='client_dime_employe_5793b8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['wire_code'], name='employee_di_wire_co_1fc59b_idx'),
        ),
    ]
