# Generated by Django 6.0.3 on 2026-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_client_dime_wire_co_bf3abe_idx_client_dime_wire_co_6e0032_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='aum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='client',
            name='client_pan',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rm_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
