# Generated by Django 6.0.3 on 2026-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_aum_client_client_pan_client_rm_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
