# Generated by Django 6.0.3 on 2026-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salesrecord_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ma_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
