# Generated by Django 6.0.3 on 2026-04-11 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_ma_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordAAABrokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rm_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ma_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wire_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('client_city', models.CharField(blank=True, max_length=100, null=True)),
                ('total_brokerage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15)),
                ('cash_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_intraday', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_cash_delivery_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_futures_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_options_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_cash_intraday_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_cash_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_fno_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokerage_records', to='core.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokerage_records', to='core.employee')),
            ],
            options={
                'db_table': 'sales_record_AAA_brokerage',
                'indexes': [models.Index(fields=['rm_name', 'total_brokerage'], name='sales_recor_rm_name_1a5aca_idx'), models.Index(fields=['client_name', 'rm_name'], name='sales_recor_client__be6af4_idx'), models.Index(fields=['period'], name='sales_recor_period_b842e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesRecordMF',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('broker_wire_code', models.CharField(blank=True, max_length=100, null=True)),
                ('mf_brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mf_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('wire_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('client_pan', models.CharField(db_index=True, default='NO PAN', max_length=20)),
                ('rm_name', models.CharField(db_index=True, default='Nitin Mude', max_length=255)),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_city', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_sales_records', to='core.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mf_sales_records', to='core.employee')),
            ],
            options={
                'db_table': 'sales_record_MF',
                'indexes': [models.Index(fields=['client_name', 'rm_name'], name='sales_recor_client__7999fb_idx'), models.Index(fields=['client_pan'], name='sales_recor_client__d9d290_idx'), models.Index(fields=['period'], name='sales_recor_period_da5bda_idx')],
            },
        ),
    ]
