# Generated by Django 6.0.3 on 2026-04-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_salesrecordaaabrokerage_salesrecordmf'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecordmf',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecordmf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
