# Generated by Django 6.0.3 on 2026-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesrecordmf_transaction_id_alter_salesrecordmf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_landing_tab',
            field=models.CharField(blank=True, default='Overall', max_length=50),
        ),
    ]
