# Generated by Django 6.0.3 on 2026-04-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_default_landing_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='operational_city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['operational_city'], name='employee_di_operati_c147c8_idx'),
        ),
    ]
