# Generated by Django 6.0.3 on 2026-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_operational_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPMSAIF',
            fields=[
                ('client_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('rm_name', models.CharField(db_index=True, max_length=255)),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('onboarded_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wire_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('aum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rm_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('ma_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ma_pan', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'client_dimension_PMSAIF',
            },
        ),
        migrations.CreateModel(
            name='ClientWealthMagic',
            fields=[
                ('client_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('rm_name', models.CharField(db_index=True, max_length=255)),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('onboarded_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wire_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('aum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('client_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rm_pan', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'client_dimension_wealthmagic',
            },
        ),
    ]
