# Generated by Django 6.0.3 on 2026-04-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clientpmsaif_clientwealthmagic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpmsaif',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='clientwealthmagic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientpmsaif',
            name='client_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientwealthmagic',
            name='client_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='clientpmsaif',
            unique_together={('client_code', 'client_name', 'rm_name')},
        ),
        migrations.AlterUniqueTogether(
            name='clientwealthmagic',
            unique_together={('client_code', 'client_name', 'rm_name')},
        ),
    ]
