# Generated by Django 6.0.3 on 2026-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clientpmsaif_id_clientwealthmagic_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecordPMSAIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('pms', 'PMS'), ('aif', 'AIF')], db_index=True, max_length=10)),
                ('rm_pan', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rm_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pms_aum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('aif_aum', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_record_PMSAIF',
                'indexes': [models.Index(fields=['client_pan', 'type'], name='sales_recor_client__4dd37a_idx'), models.Index(fields=['rm_name'], name='sales_recor_rm_name_f87567_idx'), models.Index(fields=['period'], name='sales_recor_period_b56fca_idx')],
            },
        ),
    ]
